[project]
name = "python-realtime"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "langchain-core",
    "langchain",
]

[project.optional-dependencies]
elevenlabs = ["elevenlabs"]
openai = ["langchain-openai"]
